window.markerTypes = {
  "family": "marker-fam",
  "gov":    "marker-gov",
  "video":   "marker-video",
  "picture":   "marker-picture",
  "news":   "marker-news",
  "social": "marker-soc"
};
window.infoTypes = {
  "picture": "info-picture",
  "video":   "info-video",
  "youtube":   "info-youtube",
  "tweet":   "info-tweet"
};

window.mapInfo = [
    {
        "description": "        <div id=\"blurb-legend\">            <h3>How to use this immersive</h3>            <div class=\"howto\">                <div><div class=\"images\"><img src=\"img/icon-streetview-pegman.png\" alt=\"pegman\" width=\"25\" height=\"28\" style=\"margin-left:10px;\"></div> <div style=\"padding-top: 2px;\">Move around! This uses Street View.</div></div>                <div><div class=\"images\"><img src=\"img/prev.png\" alt=\"previous\" width=\"25\" height=\"25\"><img src=\"img/next.png\" alt=\"next\" width=\"25\" height=\"25\"></div> <div style=\"padding-top: 0px;\">Travel to different places and times with arrows in the navigation bar.</div></div>                <div><div class=\"images\"><div class=\"fi-volume\" style=\"font-size:25px;padding-right:7px;\"></div><div class=\"fi-volume-strike\" style=\"font-size:25px;\"></div></div> <div style=\"padding-top: 0px;\">Some views have ambient sound. Toggle using this icon.</div></div>            </div>            <h3>Markers</h3>            <div class=\"markers\">                <div><img src=\"img/video.png\" alt=\"video\" width=\"25\" height=\"28\"> Video</div>                <div><img src=\"img/picture.png\" alt=\"picture\" width=\"25\" height=\"28\"> Picture</div>            </div>                    </div>",
        "title": "The Epicentre",
        "credit": "",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.video,
                "credit": "",
                "headline": "The first week of Occupy Central in five minutes",
                "content": "3d8k6g",
                "lat": 22.279528,
                "slide": "epicentre",
                "link": "http://www.scmp.com/video/hong-kong/1609107/recap-hong-kongs-umbrella-movement-5-minutes",
                "date": "The first week of Occupy Central in 5 minutes",
                "lng": 114.166535,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "",
                "headline": "Timelapse of the rally on October 10",
                "content": "4u2p7q",
                "lat": 22.279559,
                "slide": "epicentre",
                "link": "http://www.scmp.com/video/hong-kong/1614365/timelapse-thousands-join-rally-students-vow-escalate-protests-occupy-hong",
                "date": "October 10, 2014",
                "lng": 114.165706,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "",
                "headline": "October 2: A day at Occupy Central",
                "content": "2d0w0c",
                "lat": 22.279628,
                "slide": "epicentre",
                "link": "http://www.scmp.com/video/hong-kong/1608724/hong-kong-day-occupy-central",
                "date": "October 2, 2014",
                "lng": 114.165491,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Edward Wong/SCMP",
                "headline": "Speaker's stand",
                "content": "scmp_10oct14_ns_ocan32_ci6e8085a_46083527.jpg",
                "lat": 22.279838,
                "slide": "epicentre",
                "link": "http://www.scmp.com/news/hong-kong/article/1613434/live-liaison-office-website-targeted-hackers-government-cancels-talks?page=a",
                "date": "October 7, 2014",
                "lng": 114.165281,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "K.Y. Cheng/SCMP",
                "headline": "Study area",
                "content": "scmp_14oct14_ns_admiralty3_k_y4055a_46157779.jpg",
                "lat": 22.279814,
                "slide": "epicentre",
                "link": "http://www.scmp.com/news/hong-kong/article/1623270/study-area-admiralty-protest-zone-breath-fresh-air",
                "date": "Study area",
                "lng": 114.165134,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Cedric Sam",
                "headline": "Lennon Wall",
                "content": "lennon_wall.jpg",
                "lat": 22.279889,
                "slide": "epicentre",
                "link": "http://www.scmp.com/news/hong-kong/article/1618852/website-works-display-protesters-notes-lennon-wall",
                "date": "October 25, 2014",
                "lng": 114.166157,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "May Tse/SCMP",
                "headline": "Umbrella Man",
                "content": "scmp_06oct14_ns_cgo8_img_5704a_46003071.jpg ",
                "lat": 22.279748,
                "slide": "epicentre",
                "link": "http://www.scmp.com/news/hong-kong/article/1653496/hong-kong-volunteers-race-against-time-save-occupy-artworks",
                "date": "October 6, 2014",
                "lng": 114.165842,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Cedric Sam",
                "headline": "October 2: International TV journalists, such as Ali Moore for the BBC, reported live in Hong Kong from a footbridge overlooking the protest site",
                "content": "dsc08176.jpg",
                "lat": 22.279673,
                "slide": "epicentre",
                "link": "http://www.scmp.com/news/hong-kong/article/1542677/organiser-occupy-central-poll-hopes-international-media-will-put",
                "date": "October 2: Ali Moore for the BBC reporting live in Hong Kong",
                "lng": 114.165255,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Adolfo Arranz",
                "headline": "September 28 at 3pm: Students gathered here a few hours before taking over Harcourt Road",
                "content": "occupycentral-01.png",
                "lat": 22.279384,
                "slide": "epicentre,admiralty_centre",
                "link": "http://multimedia.scmp.com/adolfo-umbrellas/",
                "date": "September 28 3pm: Students gathered here a few hours before taking over Harcourt Rd",
                "lng": 114.165064,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "December 1: Protesters fight with suspected undercover police officers",
                "content": "7d8b9s",
                "lat": 22.279248,
                "slide": "epicentre,admiralty_centre",
                "link": "http://www.scmp.com/video/hong-kong/1652942/occupy-protesters-fight-suspected-undercover-police-officers-one-knocked-out",
                "date": "December 1: Protesters fight with suspected undercover police officers",
                "lng": 114.16514,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Edward Wong/SCMP",
                "headline": "December 1: Protesters put barricades at the bottom of the escalators leading up to Tamar Park and the Central Government Offices",
                "content": "scmp_01dec14_ns_oc39_edw_3784a_47043491.jpg",
                "lat": 22.279529,
                "slide": "epicentre,admiralty_centre",
                "link": "http://www.scmp.com/news/hong-kong/article/1652038/student-leaders-seek-send-message-move-occupiers-streets",
                "date": "December 1: Protesters put barricades at the bottom of the escalators leading up to Tamar Park and the Central Government Offices",
                "lng": 114.16526,
                "type": window.markerTypes.picture
            }
        ],
        "heading": 320,
        "lat": 22.2794343,
        "author": "",
        "pitch": "",
        "date": "Occupy Central",
        "lng": 114.1666265,
        "pano": "",
        "id": "epicentre"
    },
    {
        "description": "A week before the occupation of streets started, 13,000 people attended a rally at The Chinese University of Hong Kong.",
        "title": "Class Boycott at CUHK",
        "credit": "chichuen wong",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.youtube,
                "credit": "Young Post",
                "headline": "University class boycott at CUHK",
                "content": "_W5rLb88k_g",
                "lat": 22.4194,
                "slide": "cuhk",
                "link": "http://yp.scmp.com/news/hong-kong/article/90901/class-boycott-kicks-chinese-university",
                "date": "YoungPost reports from CUHK",
                "lng": 114.20595,
                "type": window.markerTypes.video
            }
        ],
        "heading": 180,
        "lat": 22.4195317,
        "author": "",
        "pitch": "",
        "date": "September 22 2014",
        "lng": 114.205935,
        "pano": "NNm5rzQE2TAAAAQYPJ96lQ",
        "id": "cuhk"
    },
    {
        "description": "Students attempted to enter Civic Square on the east side of the Central Government Offices on September 26 at 10.30pm.",
        "title": "Students storm Civic Square",
        "credit": "",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "September 26: Riot police deployed after Hong Kong students storm Civic Square",
                "content": "0j3g8w",
                "lat": 22.280388,
                "slide": "storm_civic_square",
                "link": "http://www.scmp.com/news/hong-kong/article/1601262/chaotic-scenes-students-break-civic-square-class-boycott-ends",
                "date": "Riot police deployed after Hong Kong students storm Civic Square",
                "lng": 114.166282,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "Joshua Wong is arrested for first time: portrait of the Scholarism leader",
                "content": "9v9e3y",
                "lat": 22.280506,
                "slide": "storm_civic_square",
                "link": "http://www.scmp.com/video/hong-kong/1601854/who-joshua-wong",
                "date": "Portrait of Joshua Wong, September 2014",
                "lng": 114.16617,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "September 27: Scuffles on Lung Wui Road in front of Legco entrance and 'start' of Occupy declared",
                "content": "7f3i7u",
                "lat": 22.280897,
                "slide": "storm_civic_square",
                "link": "http://www.scmp.com/video/hong-kong/1605016/end-two-night-student-movement-benny-tai-declares-start-occupy-central",
                "date": "September 27: Scuffles on Lung Wui Street in front of Legco entrance and 'start' of Occupy declared",
                "lng": 114.166597,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Cedric Sam",
                "headline": "October 25: At the height of movement, then-SCMP artist Adolfo Arranz sketches under an umbrella sculpture at the roundabout in front of the Legco complex",
                "content": "dsc09567.jpg",
                "lat": 22.280987,
                "slide": "storm_civic_square",
                "link": "http://multimedia.scmp.com/adolfo-umbrellas/",
                "date": "October 25: At the height of Occupy Central, then-SCMP artist Adolfo Arranz sketches under an umbrella sculpture at the roundabout in front of Legco Complex",
                "lng": 114.166784,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "September 26: Around 100 protesters break into Civic Square",
                "content": "scmp_26sep14_ns_cgo3_img_9890a_45781559.jpg",
                "lat": 22.280335,
                "slide": "storm_civic_square",
                "link": "http://www.scmp.com/news/hong-kong/article/1601625/hong-kong-students-beat-us-it-benny-tai-declares-start-occupy-central",
                "date": "September 26: Around 100 protesters broke into Civic Square",
                "lng": 114.166262,
                "type": window.markerTypes.picture
            }
        ],
        "heading": 320,
        "lat": 22.28035,
        "author": "",
        "pitch": "",
        "date": "September 26-27 2014",
        "lng": 114.1665342,
        "pano": "",
        "id": "storm_civic_square"
    },
    {
        "description": "In the afternoon of September 28, protesters gathered in Admiralty and took over Connaught Road Central in front of the Government's main offices. Hong Kong Police responded by trying to disperse the crowd with tear gas. This triggered the start of Occupy Central, also known overseas as the Umbrella Movement. <div class=\"sound\">Sound: Scuffles at this very spot outside the Central Government Offices in the afternoon of September 28, with protesters trying to break up metal barriers setup by the police.</div>",
        "title": "Dawn of Occupy Central",
        "credit": "",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "In the afternoon",
                "content": "2p0s6r",
                "lat": 22.279528,
                "slide": "dawn_occupy",
                "link": "http://www.scmp.com/video/hong-kong/1605018/police-use-pepper-spray-and-water-guns-protesters-outside-government-offices",
                "date": "In the afternoon",
                "lng": 114.166535,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "In the evening",
                "content": "9d8c3w",
                "lat": 22.279506,
                "slide": "dawn_occupy",
                "link": "http://www.scmp.com/video/hong-kong/1605019/police-fire-tear-gas-protesters-outside-hong-kong-government-offices",
                "date": "In the evening",
                "lng": 114.166316,
                "type": window.markerTypes.video
            }
        ],
        "heading": 160,
        "lat": 22.2797176,
        "author": "Cedric Sam",
        "pitch": "",
        "date": "September 28 2014",
        "lng": 114.1662837,
        "pano": "",
        "id": "dawn_occupy"
    },
    {
        "description": "After the tear gas was fired, protesters came out in force in other areas of the city, including the shopping district of Causeway Bay. A sit-in was organised on Hennessy Road and Yee Wo Street at the 'Sogo crossing'. <div class=\"sound\">Sound: Protesters resting at the intersection of Hennessy Road and Yee Wo Street on September 29 at 5:30 am. A young man shouts \"Tell the world!\" in English.</div>",
        "title": "Causeway Bay",
        "credit": "",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.youtube,
                "credit": "SCMP Video",
                "headline": "Timelapse on the evening of September 28",
                "content": "afAp6umV9QQ",
                "lat": 22.280133,
                "slide": "causeway_bay",
                "link": "http://multimedia.scmp.com/occupylapse/",
                "date": "Timelapse on the evening of September 28",
                "lng": 114.184718,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Adolfo Arranz",
                "headline": "September 29: students gather in Causeway Bay after tear gas was fired in Admiralty",
                "content": "20140930occupycentral-02.jpg",
                "lat": 22.280087,
                "slide": "causeway_bay",
                "link": "http://multimedia.scmp.com/adolfo-umbrellas/",
                "date": "September 29: students gathering in Causeway Bay after tear gas was fired in Admiralty",
                "lng": 114.184955,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Robert Ng/SCMP",
                "headline": "September 28 at 11.44 pm: Occupying the Sogo crossing",
                "content": "scmp_28sep14_ns_cwb1_rng_0.jpg",
                "lat": 22.280177,
                "slide": "causeway_bay",
                "link": "",
                "date": "September 28 23:44: Occupying the Sogo crossing",
                "lng": 114.184812,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Jonathan Wong/SCMP",
                "headline": "September 29 at 1.42 pm: Causeway Bay MTR Exit E",
                "content": "scmp_29sep14_ns_cwb14_jonw.jpg",
                "lat": 22.280354,
                "slide": "causeway_bay",
                "link": "",
                "date": "September 29 13:42: Causeway Bay MTR Exit E",
                "lng": 114.185004,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.tweet,
                "credit": "",
                "headline": "Tweet on September 29",
                "content": "<blockquote class=\"twitter-tweet\" lang=\"en\"><p>Watching the day break together <a href=\"https://twitter.com/hashtag/OccupyHK?src=hash\">#OccupyHK</a> <a href=\"https://twitter.com/hashtag/UmbrellaMovement?src=hash\">#UmbrellaMovement</a> <a href=\"http://t.co/G5psFfz4NL\">pic.twitter.com/G5psFfz4NL</a></p>&mdash; Jennifer Ngo (@jj_ngo) <a href=\"https://twitter.com/jj_ngo/status/517818097239986176\">October 2, 2014</a> <div><img src=\"https://pbs.twimg.com/media/By-o0HBCQAEh33T.jpg\" alt=\"Embedded image permalink\" width=\"420\" height=\"560\"></div></blockquote><script async src=\"//platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>",
                "lat": 22.2800935,
                "slide": "causeway_bay",
                "link": "",
                "date": "Tweet by Jennifer Ngo on September 29",
                "lng": 114.185043,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "September 30 at 3.58 am: Occupying the Sogo crossing",
                "content": "scmp_30sep14_ns_cwb20_sam.jpg",
                "lat": 22.280278,
                "slide": "causeway_bay",
                "link": "",
                "date": "September 30 at 3:58 am: Occupying the Sogo crossing",
                "lng": 114.184582,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Bruce Yan/SCMP",
                "headline": "October 3: Scuffles break out between anti-Occupy and Occupy supporters",
                "content": "scmp_03oct14_ns_occwb7_yan_2238a_45942015.jpg",
                "lat": 22.280091,
                "slide": "causeway_bay",
                "link": "http://www.scmp.com/news/hong-kong/article/1608680/live-student-protesters-await-dialogue-date-lung-wo-road-open-traffic?page=all",
                "date": "October 3: Scuffles break out between anti-Occupy and Occupy supporters",
                "lng": 114.184229,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 3: An organised group of about 30 men wearing masks broke through Hennessy Road, reaching Jardine's Bazaar, and began removing barricades there",
                "content": "0e9p0r",
                "lat": 22.280054,
                "slide": "causeway_bay",
                "link": "http://www.scmp.com/news/hong-kong/article/1608680/live-student-protesters-await-dialogue-date-lung-wo-road-open-traffic?page=all",
                "date": "October 3: An organised group of about 30 men wearing masks broke through Hennessy Road and reached Jardine's Bazaar and began removing barricades there",
                "lng": 114.18455,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.youtube,
                "credit": "SCMP Video",
                "headline": "October 14: Clearance of the westbound lane of Yee Wo Street and Hennessy Road",
                "content": "2IGWfngLM_s",
                "lat": 22.2800931,
                "slide": "causeway_bay",
                "link": "http://multimedia.scmp.com/occupylapse/#/H203F/20141015-0400",
                "date": "October 14: Clearance of the westbound lane of Yee Wo Street and Hennessy Road",
                "lng": 114.184685,
                "type": window.markerTypes.video
            }
        ],
        "heading": 120,
        "lat": 22.2802011,
        "author": "Cedric Sam",
        "pitch": "",
        "date": "Hong Kong Island",
        "lng": 114.1845722,
        "pano": "",
        "id": "causeway_bay"
    },
    {
        "description": "On October 14, part of the Occupy site in Admiralty was reclaimed and Queensway reopened, when hundreds of police officers armed with chainsaws and sledgehammers tore down barricades. One day earlier, hundreds of anti-Occupy demonstrators had clashed with Occupy protesters as they attempted to take the law into their own hands by removing barriers on the road linking Wan Chai to Central.",
        "title": "Occupation of Queensway",
        "credit": "",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.picture,
                "credit": "David Wong/SCMP",
                "headline": "October 9: Empty streets",
                "content": "scmp_09oct14_ns_admiralty8.jpg",
                "lat": 22.278944,
                "slide": "queensway",
                "link": "",
                "date": "October 9: Empty streets",
                "lng": 114.163333,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 13: Police remove some barricades as Occupy Central supporters reinforce others",
                "content": "8f8t7g",
                "lat": 22.279202,
                "slide": "queensway",
                "link": "http://www.scmp.com/video/hong-kong/1615756/hong-kong-police-remove-some-barricades-occupy-central-supporters-reinforce",
                "date": "October 13: Hong Kong Police remove some barricades as Occupy Central supporters reinforce others",
                "lng": 114.16269,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 14: Police tear down protesters\u2019 barricades in Admiralty and reopen Queensway to traffic",
                "content": "0r9g3v",
                "lat": 22.279249,
                "slide": "queensway",
                "link": "http://www.scmp.com/video/hong-kong/1615756/hong-kong-police-remove-some-barricades-occupy-central-supporters-reinforce",
                "date": "October 14: Hong Kong police tear down protesters\u2019 barricades in Admiralty and reopen Queensway to traffic",
                "lng": 114.16276,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "K.Y. Cheng/SCMP",
                "headline": "October 14: Last night of Occupy on Queensway",
                "content": "scmp_14oct14_ns_admiralty1.jpg",
                "lat": 22.279534,
                "slide": "queensway",
                "link": "",
                "date": "October 14: Last night of Occupy on Queensway",
                "lng": 114.162841,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "K.Y. Cheng/SCMP",
                "headline": "October 14: Barricade on the west side of Queensway",
                "content": "scmp_14oct14_ns_admiralty8.jpg",
                "lat": 22.2787376,
                "slide": "queensway",
                "link": "",
                "date": "October 14: Barricade on the west side of Queensway",
                "lng": 114.163501,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "K.Y. Cheng/SCMP",
                "headline": "October 14: Barricade on the east side of Queensway",
                "content": "scmp_14oct14_ns_admiralty9.jpg",
                "lat": 22.2778573,
                "slide": "queensway",
                "link": "",
                "date": "October 14: Barricade on the east side of Queensway",
                "lng": 114.1665346,
                "type": window.markerTypes.picture
            }
        ],
        "heading": 330,
        "lat": 22.279122,
        "author": "Emily Tsang",
        "pitch": "10",
        "date": "Sep 28-Oct 15",
        "lng": 114.163001,
        "pano": "",
        "id": "queensway"
    },
    {
        "description": "Surrounded by banks on all four corners, this crucial traffic intersection in Kowloon was occupied on the night of September 28, when protests spread across Victoria Harbour. Traffic on busy Nathan Road \u2013 between Dundas Street and Mong Kok Road \u2013 was paralysed and the road remained closed until it was partially reopened by police in mid-October during a pre-dawn operation. The intersection was finally opened to traffic on November 26.",
        "title": "The intersection",
        "credit": "",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.picture,
                "credit": "K.Y. Cheng/SCMP",
                "headline": "September 30: View from above of the main tent at Argyle and Nathan roads on the third day of occupation in Mong Kok",
                "content": "scmp_30sep14_ns_mk11_k_y1110a_45862035.jpg",
                "lat": 22.31934,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "September 30: View from above of the main tent at Argyle & Nathan on the third day of occupation in Mong Kok",
                "lng": 114.169452,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Cedric Sam",
                "headline": "October 6: Listening to speeches at the main tent in Mong Kok",
                "content": "dsc08460-motion_600px.gif",
                "lat": 22.319311,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "October 6: Listening to speeches at the main tent in Mong Kok",
                "lng": 114.169461,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 18: Clashes",
                "content": "0a0m2d",
                "lat": 22.319248,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1619371/violent-clashes-mong-kok-lead-arrests-and-injuries-overnight",
                "date": "October 18: Clashes",
                "lng": 114.169288,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 17: First clearance",
                "content": "8y9m1e",
                "lat": 22.319228,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1618373/traffic-near-normal-police-remove-barriers-mong-kok-remaining-protestors",
                "date": "October 17: First clearance",
                "lng": 114.169414,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 25: Second clearance",
                "content": "8p1l3v",
                "lat": 22.318857,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1649323/little-resistance-occupy-protesters-police-clear-mong-kok-barricades-arrest",
                "date": "November 25: Second clearance",
                "lng": 114.169361,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 27: Violent clashes",
                "content": "3e9v3w",
                "lat": 22.319296,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1649858/clashes-break-out-hong-kong-protesters-attempt-reoccupy-mong-kok",
                "date": "November 27: Violent clashes",
                "lng": 114.169493,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video via DBC",
                "headline": "November 28: DBC Video",
                "content": "4o8f4f",
                "lat": 22.319541,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1650771/video-broadcaster-dbc-shows-police-hitting-people-who-appear-be-leaving",
                "date": "November 28: DBC Video",
                "lng": 114.169548,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 29: Arrests, batons, dogs",
                "content": "0o8m2w",
                "lat": 22.3193814,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1651400/arrests-batons-dogs-police-aim-prevent-protesters-re-occupying-mong-kok",
                "date": "November 29: Arrests batons dogs",
                "lng": 114.1699877,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 3: First of many violent nights in Mong Kok when alleged triad members confront protesters",
                "content": "0h1h9s",
                "lat": 22.319244,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1609225/violence-breaks-out-hong-kongs-densly-populated-mong-kok-shopping-district",
                "date": "October 3: First of many violent nights in Mong Kok when alleged triad members came out against protesters",
                "lng": 114.169037,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "K.Y. Cheng/SCMP",
                "headline": "September 30: Stranded bus at the corner of Nathan and Mong Kok roads",
                "content": "scmp_30sep14_ns_mk7_k_y1032a_45862029.jpg",
                "lat": 22.3207997,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/news/hong-kong/article/1607246/occupy-protesters-reach-deal-access-fire-engines-causeway-bay",
                "date": "September 30: Stranded bus at the corner of Nathan and Mong Kok Road",
                "lng": 114.1691118,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Adolfo Arranz",
                "headline": "October 12: The barricades in Mong Kok on Nathan Road, at the corner of Shantung Street",
                "content": "mongkok.png",
                "lat": 22.317521,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://multimedia.scmp.com/adolfo-umbrellas/",
                "date": "October 12: The barricades in Mong Kok on Nathan Road, at the corner of Shantung Street",
                "lng": 114.169798,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "November 26 at 11.12 am: Clearance operation in Mong Kok occupied site, corner of Nathan Road near Soy Street",
                "content": "scmp_26nov14_ns_mongkok46_sam_7377_46958211.jpg",
                "lat": 22.316576,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "November 26 at 11:12 am: Clearance operation in Mong Kok occupied site",
                "lng": 114.169905,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "November 26 at 11.27 am: Clearance operation in Mong Kok occupied site, corner of Nathan Road and Dundas Street",
                "content": "scmp_26nov14_ns_mongkok31_sam_7551a_46957263.jpg",
                "lat": 22.31529,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "November 26 at 11:26 am: Clearance operation in Mong Kok occupied site",
                "lng": 114.170171,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 17: The religious deities of Occupy Hong Kong",
                "content": "4m1s8b",
                "lat": 22.318382,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/news/hong-kong/article/1625126/religion-occupy-central-front-line-puts-faith-practice",
                "date": "October 17: The religious deities of Occupy Hong Kong",
                "lng": 114.169547,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "David Wong/SCMP",
                "headline": "October 1: Trash bins are used to block Nathan Road at the corner with Shantung Street in Mong Kok",
                "content": "scmp_01oct14_ns_mongkok1_img_3839a_45885981.jpg",
                "lat": 22.317364,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/news/hong-kong/article/1625126/religion-occupy-central-front-line-puts-faith-practice",
                "date": "October 1: Trash bins blocking Nathan Road at the corner with Shantung Street in Mong Kok",
                "lng": 114.169806,
                "type": window.markerTypes.picture
            }
        ],
        "heading": 215,
        "lat": 22.3193323,
        "author": "Ernest Kao",
        "pitch": "",
        "date": "Nathan and Argyle (1/2)",
        "lng": 114.1693802,
        "pano": "",
        "id": "mong_kok"
    },
    {
        "description": "Surrounded by banks on all four corners, this crucial traffic intersection in Kowloon was occupied on the night of September 28, when protests spread across Victoria Harbour. Traffic on busy Nathan Road \u2013 between Dundas Street and Mong Kok Road \u2013 was paralysed and the road remained closed until it was partially reopened by police in mid-October during a pre-dawn operation. The intersection was finally opened to traffic on November 26. <div class=\"credit\">Photosphere taken on October 4</div>",
        "title": "The intersection (occupied)",
        "credit": "N john",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.picture,
                "credit": "K.Y. Cheng/SCMP",
                "headline": "September 30: View from above of the main tent at Argyle and Nathan roads on the third day of occupation in Mong Kok",
                "content": "scmp_30sep14_ns_mk11_k_y1110a_45862035.jpg",
                "lat": 22.31934,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "September 30: View from above of the main tent at Argyle & Nathan on the third day of occupation in Mong Kok",
                "lng": 114.169452,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Cedric Sam",
                "headline": "October 6: Listening to speeches at the main tent in Mong Kok",
                "content": "dsc08460-motion_600px.gif",
                "lat": 22.319311,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "October 6: Listening to speeches at the main tent in Mong Kok",
                "lng": 114.169461,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 18: Clashes",
                "content": "0a0m2d",
                "lat": 22.319248,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1619371/violent-clashes-mong-kok-lead-arrests-and-injuries-overnight",
                "date": "October 18: Clashes",
                "lng": 114.169288,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 17: First clearance",
                "content": "8y9m1e",
                "lat": 22.319228,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1618373/traffic-near-normal-police-remove-barriers-mong-kok-remaining-protestors",
                "date": "October 17: First clearance",
                "lng": 114.169414,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 25: Second clearance",
                "content": "8p1l3v",
                "lat": 22.318857,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1649323/little-resistance-occupy-protesters-police-clear-mong-kok-barricades-arrest",
                "date": "November 25: Second clearance",
                "lng": 114.169361,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 27: Violent clashes",
                "content": "3e9v3w",
                "lat": 22.319296,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1649858/clashes-break-out-hong-kong-protesters-attempt-reoccupy-mong-kok",
                "date": "November 27: Violent clashes",
                "lng": 114.169493,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video via DBC",
                "headline": "November 28: DBC Video",
                "content": "4o8f4f",
                "lat": 22.319541,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1650771/video-broadcaster-dbc-shows-police-hitting-people-who-appear-be-leaving",
                "date": "November 28: DBC Video",
                "lng": 114.169548,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 29: Arrests, batons, dogs",
                "content": "0o8m2w",
                "lat": 22.3193814,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1651400/arrests-batons-dogs-police-aim-prevent-protesters-re-occupying-mong-kok",
                "date": "November 29: Arrests batons dogs",
                "lng": 114.1699877,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 3: First of many violent nights in Mong Kok when alleged triad members confront protesters",
                "content": "0h1h9s",
                "lat": 22.319244,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1609225/violence-breaks-out-hong-kongs-densly-populated-mong-kok-shopping-district",
                "date": "October 3: First of many violent nights in Mong Kok when alleged triad members came out against protesters",
                "lng": 114.169037,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "K.Y. Cheng/SCMP",
                "headline": "September 30: Stranded bus at the corner of Nathan and Mong Kok roads",
                "content": "scmp_30sep14_ns_mk7_k_y1032a_45862029.jpg",
                "lat": 22.3207997,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/news/hong-kong/article/1607246/occupy-protesters-reach-deal-access-fire-engines-causeway-bay",
                "date": "September 30: Stranded bus at the corner of Nathan and Mong Kok Road",
                "lng": 114.1691118,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Adolfo Arranz",
                "headline": "October 12: The barricades in Mong Kok on Nathan Road, at the corner of Shantung Street",
                "content": "mongkok.png",
                "lat": 22.317521,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://multimedia.scmp.com/adolfo-umbrellas/",
                "date": "October 12: The barricades in Mong Kok on Nathan Road, at the corner of Shantung Street",
                "lng": 114.169798,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "November 26 at 11.12 am: Clearance operation in Mong Kok occupied site, corner of Nathan Road near Soy Street",
                "content": "scmp_26nov14_ns_mongkok46_sam_7377_46958211.jpg",
                "lat": 22.316576,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "November 26 at 11:12 am: Clearance operation in Mong Kok occupied site",
                "lng": 114.169905,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "November 26 at 11.27 am: Clearance operation in Mong Kok occupied site, corner of Nathan Road and Dundas Street",
                "content": "scmp_26nov14_ns_mongkok31_sam_7551a_46957263.jpg",
                "lat": 22.31529,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "November 26 at 11:26 am: Clearance operation in Mong Kok occupied site",
                "lng": 114.170171,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 17: The religious deities of Occupy Hong Kong",
                "content": "4m1s8b",
                "lat": 22.318382,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/news/hong-kong/article/1625126/religion-occupy-central-front-line-puts-faith-practice",
                "date": "October 17: The religious deities of Occupy Hong Kong",
                "lng": 114.169547,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "David Wong/SCMP",
                "headline": "October 1: Trash bins are used to block Nathan Road at the corner with Shantung Street in Mong Kok",
                "content": "scmp_01oct14_ns_mongkok1_img_3839a_45885981.jpg",
                "lat": 22.317364,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/news/hong-kong/article/1625126/religion-occupy-central-front-line-puts-faith-practice",
                "date": "October 1: Trash bins blocking Nathan Road at the corner with Shantung Street in Mong Kok",
                "lng": 114.169806,
                "type": window.markerTypes.picture
            }
        ],
        "heading": 206,
        "lat": 22.319351,
        "author": "Ernest Kao",
        "pitch": "",
        "date": "Nathan and Argyle (2/2)",
        "lng": 114.169357,
        "pano": "ba0y_EFlSkcAAAQYW2h3ZQ",
        "id": "mong_kok_occupied"
    },
    {
        "description": "The last section of the Mong Kok Occupy zone to be cleared in a court-ordered operation on November 26 was the southernmost barricade, which had the fewest people guarding it. It was often an area of concern for those who feared a surprise raid by police or anti-Occupy proponents. <div class=\"credit\">Photosphere taken on October 25</div>",
        "title": "South Mong Kok",
        "credit": "Adrian Chan",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.picture,
                "credit": "K.Y. Cheng/SCMP",
                "headline": "September 30: View from above of the main tent at Argyle and Nathan roads on the third day of occupation in Mong Kok",
                "content": "scmp_30sep14_ns_mk11_k_y1110a_45862035.jpg",
                "lat": 22.31934,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "September 30: View from above of the main tent at Argyle & Nathan on the third day of occupation in Mong Kok",
                "lng": 114.169452,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Cedric Sam",
                "headline": "October 6: Listening to speeches at the main tent in Mong Kok",
                "content": "dsc08460-motion_600px.gif",
                "lat": 22.319311,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "October 6: Listening to speeches at the main tent in Mong Kok",
                "lng": 114.169461,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 18: Clashes",
                "content": "0a0m2d",
                "lat": 22.319248,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1619371/violent-clashes-mong-kok-lead-arrests-and-injuries-overnight",
                "date": "October 18: Clashes",
                "lng": 114.169288,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 17: First clearance",
                "content": "8y9m1e",
                "lat": 22.319228,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1618373/traffic-near-normal-police-remove-barriers-mong-kok-remaining-protestors",
                "date": "October 17: First clearance",
                "lng": 114.169414,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 25: Second clearance",
                "content": "8p1l3v",
                "lat": 22.318857,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1649323/little-resistance-occupy-protesters-police-clear-mong-kok-barricades-arrest",
                "date": "November 25: Second clearance",
                "lng": 114.169361,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 27: Violent clashes",
                "content": "3e9v3w",
                "lat": 22.319296,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1649858/clashes-break-out-hong-kong-protesters-attempt-reoccupy-mong-kok",
                "date": "November 27: Violent clashes",
                "lng": 114.169493,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video via DBC",
                "headline": "November 28: DBC Video",
                "content": "4o8f4f",
                "lat": 22.319541,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1650771/video-broadcaster-dbc-shows-police-hitting-people-who-appear-be-leaving",
                "date": "November 28: DBC Video",
                "lng": 114.169548,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 29: Arrests, batons, dogs",
                "content": "0o8m2w",
                "lat": 22.3193814,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1651400/arrests-batons-dogs-police-aim-prevent-protesters-re-occupying-mong-kok",
                "date": "November 29: Arrests batons dogs",
                "lng": 114.1699877,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 3: First of many violent nights in Mong Kok when alleged triad members confront protesters",
                "content": "0h1h9s",
                "lat": 22.319244,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/video/hong-kong/1609225/violence-breaks-out-hong-kongs-densly-populated-mong-kok-shopping-district",
                "date": "October 3: First of many violent nights in Mong Kok when alleged triad members came out against protesters",
                "lng": 114.169037,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "K.Y. Cheng/SCMP",
                "headline": "September 30: Stranded bus at the corner of Nathan and Mong Kok roads",
                "content": "scmp_30sep14_ns_mk7_k_y1032a_45862029.jpg",
                "lat": 22.3207997,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/news/hong-kong/article/1607246/occupy-protesters-reach-deal-access-fire-engines-causeway-bay",
                "date": "September 30: Stranded bus at the corner of Nathan and Mong Kok Road",
                "lng": 114.1691118,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Adolfo Arranz",
                "headline": "October 12: The barricades in Mong Kok on Nathan Road, at the corner of Shantung Street",
                "content": "mongkok.png",
                "lat": 22.317521,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://multimedia.scmp.com/adolfo-umbrellas/",
                "date": "October 12: The barricades in Mong Kok on Nathan Road, at the corner of Shantung Street",
                "lng": 114.169798,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "November 26 at 11.12 am: Clearance operation in Mong Kok occupied site, corner of Nathan Road near Soy Street",
                "content": "scmp_26nov14_ns_mongkok46_sam_7377_46958211.jpg",
                "lat": 22.316576,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "November 26 at 11:12 am: Clearance operation in Mong Kok occupied site",
                "lng": 114.169905,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "November 26 at 11.27 am: Clearance operation in Mong Kok occupied site, corner of Nathan Road and Dundas Street",
                "content": "scmp_26nov14_ns_mongkok31_sam_7551a_46957263.jpg",
                "lat": 22.31529,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "",
                "date": "November 26 at 11:26 am: Clearance operation in Mong Kok occupied site",
                "lng": 114.170171,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 17: The religious deities of Occupy Hong Kong",
                "content": "4m1s8b",
                "lat": 22.318382,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/news/hong-kong/article/1625126/religion-occupy-central-front-line-puts-faith-practice",
                "date": "October 17: The religious deities of Occupy Hong Kong",
                "lng": 114.169547,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "David Wong/SCMP",
                "headline": "October 1: Trash bins are used to block Nathan Road at the corner with Shantung Street in Mong Kok",
                "content": "scmp_01oct14_ns_mongkok1_img_3839a_45885981.jpg",
                "lat": 22.317364,
                "slide": "mong_kok,mong_kok_occupied,south_mong_kok",
                "link": "http://www.scmp.com/news/hong-kong/article/1625126/religion-occupy-central-front-line-puts-faith-practice",
                "date": "October 1: Trash bins blocking Nathan Road at the corner with Shantung Street in Mong Kok",
                "lng": 114.169806,
                "type": window.markerTypes.picture
            }
        ],
        "heading": 160,
        "lat": 22.3155042,
        "author": "Ernest Kao",
        "pitch": "",
        "date": "Nathan and Dundas",
        "lng": 114.169998,
        "pano": "gdu4qEVLDdQAAAQYn9ZhBw",
        "id": "south_mong_kok"
    },
    {
        "description": "One of Hong Kong's most iconic peaks saw a makeover on October 23 when a 28-metre-long banner was unfurled from the top of the Lion Rock in Kowloon. Emblazoned with the words \u2018I want real universal suffrage\u2019, the banner could be seen from different areas of northern Kowloon, including straight ahead from this spot in Wong Tai Sin. A group calling itself The Hong Kong Spidie, after comic book hero Spider-Man, claimed responsibility for the stunt. News and images of the impressive feat went viral within minutes and the yellow banner became a key symbol of the democracy movement. The banner was quickly removed by authorities.",
        "title": "Banner on Lion's Rock",
        "credit": "",
        "zoom": "2",
        "markers": [
            {
                "infotype": window.infoTypes.picture,
                "credit": "Robert Ng/SCMP",
                "headline": "October 23: Banner on Lion Rock",
                "content": "scmp_24oct14_ns_lion1_rng_2133a_46343767.jpg",
                "lat": 22.3427,
                "slide": "lion_rock",
                "link": "http://www.scmp.com/news/hong-kong/article/1622971/climbers-hang-giant-banner-lion-rock-calling-real-universal-suffrage",
                "date": "October 23: Banner on Lion Rock",
                "lng": 114.188837,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.youtube,
                "credit": "",
                "headline": "October 23: Banner on Lion Rock (video)",
                "content": "iEQ2rj-7DDE",
                "lat": 22.3427,
                "slide": "lion_rock",
                "link": "http://www.scmp.com/news/hong-kong/article/1622971/climbers-hang-giant-banner-lion-rock-calling-real-universal-suffrage",
                "date": "October 23: Banner on Lion Rock (video)",
                "lng": 114.188887,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "Ray Ng makes a model of Lion Rock Hill at the main protest site in Admiralty",
                "content": "scmp_03nov14_ns_admiralty6_sam_8218a_46524221.jpg",
                "lat": 22.3427,
                "slide": "lion_rock",
                "link": "http://www.scmp.com/news/hong-kong/article/1631127/if-occupy-cant-come-mountain-replica-lion-rock-unveiled-admiralty",
                "date": "Ray Ng making a model of Lion Rock Hill at the main protest site in Admiralty",
                "lng": 114.188937,
                "type": window.markerTypes.picture
            }
        ],
        "heading": 340,
        "lat": 22.3423764,
        "author": "Ernest Kao",
        "pitch": "5",
        "date": "October 23 2014",
        "lng": 114.189063,
        "pano": "",
        "id": "lion_rock"
    },
    {
        "description": "While the movement in Mong Kok waned, a hardcore group of protesters continued to demonstrate at various locations throughout the neighbourhood. The intersection of Sai Yeung Choi Street and Soy Street was the scene of violent scuffles in the week Nathan Road was cleared, leading to the controversial arrest of an Apple Daily cameraman.",
        "title": "Shopping' on Sai Yeung Choi Street",
        "credit": "Tommy Hung",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 28: An Apple Daily cameraman is arrested",
                "content": "0h3w8c",
                "lat": 22.316668,
                "slide": "shopping",
                "link": "http://www.scmp.com/news/hong-kong/article/1650334/new-video-emerges-apple-daily-photographer-being-arrested-mong-kok",
                "date": "November 28: Apple Daily cameraman being arrested",
                "lng": 114.170485,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Felix Wong/SCMP",
                "headline": "November 27: At the corner of Soy Street and Sai Yeung Choi Street",
                "content": "scmp_27nov14_ns_ocmkf5_wck_6954a_46973725.jpg",
                "lat": 22.3168,
                "slide": "shopping",
                "link": "http://www.scmp.com/news/hong-kong/article/1649073/angry-nightly-standoff-mong-kok-amid-occupy-clearance-attempts",
                "date": "November 27: At the corner of Soy Street and Sai Yeung Choi Street",
                "lng": 114.170485,
                "type": window.markerTypes.picture
            }
        ],
        "heading": 280,
        "lat": 22.31669,
        "author": "Cedric Sam",
        "pitch": "",
        "date": "November 28 2014",
        "lng": 114.170557,
        "pano": "anUiEQekB4MAAAAGOyk4Dw",
        "id": "shopping"
    },
    {
        "description": "The Hong Kong Police headquarters on Arsenal Street sits just around the corner from the main protest site in Admiralty. In the first week of Occupy, the roads around it were closed and protesters coming from Wan Chai would often pass by. On October 15, following the beating of protester Ken Tsang, a crowd gathered outside the building to protest police brutality.",
        "title": "Arsenal Street, Wan Chai",
        "credit": "",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.youtube,
                "credit": "SCMP Video",
                "headline": "Timelapse on October 1",
                "content": "ARwqDNcZBnA",
                "lat": 22.27806,
                "slide": "police_hq",
                "link": "http://multimedia.scmp.com/occupylapse/#/H201F/20141002-1600",
                "date": "Timelapse on October 1",
                "lng": 114.168416,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Cedric Sam",
                "headline": "October 2: Occupiers take over the highway entrance on Arsenal Street in the early days of the movement",
                "content": "dsc08123.jpg",
                "lat": 22.278686,
                "slide": "police_hq",
                "link": "",
                "date": "October 2: Occupiers took over the highway entrance on Arsenal Street in the early days of the movement",
                "lng": 114.168833,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 15: Hundreds of protesters occupy Arsenal Street outside police headquarters",
                "content": "2k2s3r",
                "lat": 22.278501,
                "slide": "police_hq",
                "link": "http://www.scmp.com/video/hong-kong/1617209/hundreds-protesters-occupy-arsenal-street-outside-police-headquarters",
                "date": "October 15: Hundreds of protesters occupy Arsenal Street outside police headquarters",
                "lng": 114.168683,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Nora Tam/SCMP",
                "headline": "October 15: Hundreds of protesters occupy Arsenal Street outside police headquarters",
                "content": "scmp_15oct14_ns_policehq5_img_0331a_46180707.jpg",
                "lat": 22.278401,
                "slide": "police_hq",
                "link": "http://www.scmp.com/news/hong-kong/article/1616671/live-police-clash-occupy-protesters-attempt-clear-lung-wo-road",
                "date": "October 15: Hundreds of protesters occupy Arsenal Street outside police headquarters",
                "lng": 114.1687,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Edward Wong/SCMP",
                "headline": "October 26: HKJA's Sham Yee-lan and Erik Mak Ka-wai of RTHK hand a petition to police after reporters were assaulted at an anti-Occupy rally",
                "content": "scmp_26oct14_ns_protest1_46383745.jpg",
                "lat": 22.278745,
                "slide": "police_hq",
                "link": "http://www.scmp.com/article/1625066/journalists-condemn-attacks-reporters-covering-protests?comment-sort=recommended",
                "date": "October 26: HKJA's Sham Yee-lan and Erik Mak Ka-wai of RTHK hand in the petition hand petition to police after assault on reporters the night before during an anti-Occupy rally",
                "lng": 114.168703,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "December 7: Hundreds of parents attend a march towards the police headquarters to protest against heavy-handed tactics",
                "content": "scmp_07dec14_ns_parent13_sam_1317_47146733.jpg",
                "lat": 22.278611,
                "slide": "police_hq",
                "link": "http://www.scmp.com/news/hong-kong/article/1657260/protesters-seek-legal-advice-over-abuse-while-detained",
                "date": "December 7: Hundreds of parents attended a march to police headquarters to protest against the police tactics",
                "lng": 114.168626,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "November 12: Protesters march to the police headquarters after the arrest of Occupy Central marshals",
                "content": "3e7m2d",
                "lat": 22.279066,
                "slide": "police_hq",
                "link": "http://www.scmp.com/news/hong-kong/article/1638941/occupy-central-marshals-arrested-fighting-join-march-protest-charges",
                "date": "November 12: Protesters march to the police headquarters after the arrest of Occupy Central marshals",
                "lng": 114.168872,
                "type": window.markerTypes.video
            }
        ],
        "heading": 300,
        "lat": 22.2785076,
        "author": "Cedric Sam",
        "pitch": "",
        "date": "Police Headquarters",
        "lng": 114.16876,
        "pano": "",
        "id": "police_hq"
    },
    {
        "description": "Most people who took the MTR to the Admiralty protest site on Harcourt Road caught their first glimpse of the movement in the Admiralty Centre, where the walls were full of banners and posters.",
        "title": "The bottleneck",
        "credit": "Global For HK",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.picture,
                "credit": "Adolfo Arranz",
                "headline": "September 28 at 3pm: Students gathered here a few hours before taking over Harcourt Road",
                "content": "occupycentral-01.png",
                "lat": 22.279384,
                "slide": "epicentre,admiralty_centre",
                "link": "http://multimedia.scmp.com/adolfo-umbrellas/",
                "date": "September 28 3pm: Students gathered here a few hours before taking over Harcourt Rd",
                "lng": 114.165064,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "December 1: Protesters fight with suspected undercover police officers",
                "content": "7d8b9s",
                "lat": 22.279248,
                "slide": "epicentre,admiralty_centre",
                "link": "http://www.scmp.com/video/hong-kong/1652942/occupy-protesters-fight-suspected-undercover-police-officers-one-knocked-out",
                "date": "December 1: Protesters fight with suspected undercover police officers",
                "lng": 114.16514,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Edward Wong/SCMP",
                "headline": "December 1: Protesters put barricades at the bottom of the escalators leading up to Tamar Park and the Central Government Offices",
                "content": "scmp_01dec14_ns_oc39_edw_3784a_47043491.jpg",
                "lat": 22.279529,
                "slide": "epicentre,admiralty_centre",
                "link": "http://www.scmp.com/news/hong-kong/article/1652038/student-leaders-seek-send-message-move-occupiers-streets",
                "date": "December 1: Protesters put barricades at the bottom of the escalators leading up to Tamar Park and the Central Government Offices",
                "lng": 114.16526,
                "type": window.markerTypes.picture
            }
        ],
        "heading": 200,
        "lat": 22.2794659,
        "author": "Emily Tsang",
        "pitch": "",
        "date": "Admiralty Centre",
        "lng": 114.1651637,
        "pano": "dXvsFfqWOEQAAAQYfeuo2w",
        "id": "admiralty_centre"
    },
    {
        "description": "The area around Lung Wo Road saw numerous violent scuffles in mid-October and late November, as protesters in Admiralty made repeated attempts to occupy the route outside the Chief Executive\u2019s Office. Police were determined to keep the major east-west thoroughfare unobstructed.",
        "title": "The battleground",
        "credit": "Global For HK",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.picture,
                "credit": "Cedric Sam",
                "headline": "October 5: Minibuses wait at spots away from their usual routes. Many drivers were affected by the Occupy struggle.",
                "content": "dsc08253.jpg",
                "lat": 22.282433,
                "slide": "lung_wo_tamar",
                "link": "http://www.scmp.com/news/hong-kong/article/1561746/about-60-minibus-drivers-stage-sit-against-planned-occupy-central",
                "date": "October 5: Minibuses waited for clients at a different spot than usual and they have played a central role in the Occupy struggle",
                "lng": 114.164734,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video via TVB",
                "headline": "October 15: Beating of Ken Tsang",
                "content": "2b1j2n",
                "lat": 22.282666,
                "slide": "lung_wo_tamar",
                "link": "http://www.scmp.com/video/hong-kong/1616887/hong-kongs-tvb-television-station-airs-video-alleged-police-beating-occupy",
                "date": "October 15: Beating of Ken Tsang",
                "lng": 114.164731,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 14: Reoccupation of Lung Wo Road",
                "content": "8l5t0j",
                "lat": 22.282356,
                "slide": "lung_wo_tamar",
                "link": "http://www.scmp.com/video/hong-kong/1616650/protesters-re-occupy-lung-wo-rd-admiralty-after-clash-police",
                "date": "October 14: Reoccupation of Lung Wo Road",
                "lng": 114.165318,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Nora Tam/SCMP",
                "headline": "October 14: Reoccupation of Lung Wo Road",
                "content": "scmp_14oct14_ns_tamar10_im.jpg",
                "lat": 22.282278,
                "slide": "lung_wo_tamar",
                "link": "http://www.scmp.com/news/hong-kong/article/1615997/live-causeway-bay-protesters-vow-rebuild-barricades-after-police",
                "date": "October 14: Reoccupation of Lung Wo Road",
                "lng": 114.165816,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "October 15: Pepper spray",
                "content": "5q7d7u",
                "lat": 22.282757,
                "slide": "lung_wo_tamar",
                "link": "http://www.scmp.com/video/hong-kong/1616741/hong-kong-police-use-pepper-spray-lung-wo-road-clear-out-operation",
                "date": "October 15: Pepper Spray",
                "lng": 114.165569,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Alex Ogle/AFP",
                "headline": "October 15: Pepper spray",
                "content": "topshots-hong_kong-china-politics-democracy_amo00_46177623.jpg",
                "lat": 22.282757,
                "slide": "lung_wo_tamar",
                "link": "http://www.scmp.com/news/hong-kong/article/1616671/live-police-clash-occupy-protesters-attempt-clear-lung-wo-road",
                "date": "October 15: Pepper Spray",
                "lng": 114.165569,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "December 1: Violent clashes",
                "content": "9i2k5t",
                "lat": 22.282649,
                "slide": "lung_wo_tamar",
                "link": "http://www.scmp.com/video/hong-kong/1652955/violent-clashes-admiralty-overnight-after-hong-kong-protests-escalate",
                "date": "December 1: Violent clashes",
                "lng": 114.165066,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "December 1: Protests escalate",
                "content": "2g8l9h",
                "lat": 22.282582,
                "slide": "lung_wo_tamar",
                "link": "http://www.scmp.com/video/hong-kong/1652767/hong-kong-protesters-clash-police-admiralty-occupy-movement-escalates",
                "date": "December 1: Protesters escalate",
                "lng": 114.165688,
                "type": window.markerTypes.video
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "December 1: Police officers clash with pro-democracy protesters",
                "content": "scmp_01dec14_ns_cgo24_sam_0296a_47042577.jpg",
                "lat": 22.2822,
                "slide": "lung_wo_tamar",
                "link": "http://www.scmp.com/news/hong-kong/article/1652860/live-occupy-students-clash-police-near-hong-kongs-government",
                "date": "December 1: Police officers clash with pro-democracy protesters",
                "lng": 114.164959,
                "type": window.markerTypes.picture
            }
        ],
        "heading": 280,
        "lat": 22.2825426,
        "author": "Emily Tsang",
        "pitch": "",
        "date": "Lung Wo Rd & Tamar Park",
        "lng": 114.1651991,
        "pano": "XQMwDuILVeAAAAQYfeuovQ",
        "id": "lung_wo_tamar"
    },
    {
        "description": "This portion of highway in Admiralty was the main occupation site and gathering point for the movement's largest rallies. Many banners hung from the footbridge linking Admiralty Centre to the government offices. <div class=\"sound\">Sound: Crowd in Admiralty on September 28 singing <em>Boundless Sea and Sky</em> by 1980s Hong Kong band Beyond.</div><div class=\"credit\">Photosphere taken on October 19</div>",
        "title": "Last days of Occupy?",
        "credit": "chichuen wong",
        "zoom": "",
        "markers": [
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "November 17: Banners in Admiralty referencing lyrics to one of the protest's theme songs",
                "content": "scmp_17nov14_ns_admiralty1_sam_1986a_46792265.jpg",
                "lat": 22.279992,
                "slide": "last_days",
                "link": "",
                "date": "November 17: Banners in Admiralty referencing lyrics to one of the protest's theme songs",
                "lng": 114.165592,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.picture,
                "credit": "Sam Tsang/SCMP",
                "headline": "December 7: Police recently estimated that the number of protesters remaining in Admiralty between 8am and 9am was just over 100",
                "content": "scmp_07dec14_ns_occupy4_sam_0776a_47146167.jpg",
                "lat": 22.279617,
                "slide": "last_days",
                "link": "",
                "date": "December 7: Police recently estimated that the number of protesters remaining in Admiralty between 8am and 9am was just over 100",
                "lng": 114.165752,
                "type": window.markerTypes.picture
            },
            {
                "infotype": window.infoTypes.video,
                "credit": "SCMP Video",
                "headline": "December 11: Clearance day",
                "content": "7t0n0c",
                "lat": 22.279712,
                "slide": "last_days",
                "link": "http://www.scmp.com/news/hong-kong/article/1660285/live-occupy-protesters-pack-and-say-their-goodbyes-hong-kong-police",
                "date": "December 11: Clearance day",
                "lng": 114.165654,
                "type": window.markerTypes.video
            }
        ],
        "heading": 32,
        "lat": 22.27971,
        "author": "Emily Tsang & Cedric Sam",
        "pitch": "",
        "date": "October 2014",
        "lng": 114.1655983,
        "pano": "PLar7rSC_j8AAAQYi103dA",
        "id": "last_days"
    }
];
